### ISSUE TITLE
certain character makes theme doesn't work

### ISSUE THREAD

**Issue by BurgerTown** [spencerwoo98/awesome-alias#1]
`#$prompt += Write-Prompt -Object "╭" -ForegroundColor $sl.Colors.PromptIndicatorForegroundColor1`
`#$prompt += Write-Prompt -Object "╰" -ForegroundColor $sl.Colors.PromptIndicatorForegroundColor1`
themes doesn't work with those"╭" and "╰" in theme setting
works without them

![default](https://user-images.githubusercontent.com/19660419/50747062-e8063680-126c-11e9-8b24-edacf5c06560.png)

**Comment by spencerwooo** [comment]
试试 NerdFont？https://github.com/ryanoasis/nerd-fonts

**Comment by BurgerTown** [comment]
> 
> 
> 试试 NerdFont？https://github.com/ryanoasis/nerd-fonts

字体用的就是NerdFont 里 Iosevka

![default](https://user-images.githubusercontent.com/19660419/50749102-a4fd9080-1277-11e9-88cd-e1833b6c8801.png)

有这两个符号powershell就不加载主题了。。。 "╭" and "╰"

**Comment by spencerwooo** [comment]
你用的是 PowerShell 那个自带终端还是别的终端模拟器啊？（不知道跟这个有没有关系但是我在 PowerShell 终端里面也能正常显示这个字符）

**Comment by BurgerTown** [comment]
用的Cmder 但是只要是加了那两行 PS也不能加载主题

**Comment by spencerwooo** [comment]
emm 这个不知道，我没遇到这个问题

**Comment by BurgerTown** [comment]
我怀疑跟ps的版本有关。。

**Comment by spencerwooo** [comment]
<img width="693" alt="powershell_wgc3cfh631" src="https://user-images.githubusercontent.com/32114380/50769537-36dcbc00-12bf-11e9-9ca3-b40b09c85dc0.png">

嗯，我这确实没问题的，又确认了一遍，不知道你那什么问题

**Comment by BurgerTown** [comment]
好吧
