### ISSUE TITLE
Hyper上prompt显示异常

### ISSUE THREAD

**Issue by Whale-fall** [spencerwoo98/awesome-alias#2]
![Snipaste_2019-05-23_11-13-10](https://user-images.githubusercontent.com/22662209/58223336-cd2fec80-7d4b-11e9-9367-9a0688a80f2b.png)
如图，会有很奇怪的框线

**Comment by spencerwooo** [comment]
好像这是 Hyper 本身的渲染问题。可以考虑：

- 改变字体（比如 [FuraCode NF](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode)）
- 更换使用 [Fluent Terminal](https://github.com/felixse/FluentTerminal)

详细请看文章：https://sspai.com/post/52868

**Comment by Whale-fall** [comment]
更沙黑体的话应该是支持特殊字符的吧，之前使用没有问题，但是更新到1903后就出现了这样的框线，fluent terminal显示正常，但是奇怪的是输入参数比如colortool -s时，“-S”的颜色和背景色一模一样根本分辨不出来输入了什么，以及fluent 渲染的色调有点怪怪的
![Snipaste_2019-05-25_14-01-23](https://user-images.githubusercontent.com/22662209/58365344-9ac1f300-7ef5-11e9-8269-bd1f48487564.png)
