### ISSUE TITLE
colortool设置后，powershell的参数选项和背景色一致，无法区分。

### ISSUE THREAD

**Issue by Whale-fall** [spencerwoo98/awesome-alias#3]
比如在这里，我输入的命令是colortool -s s，实际的显示效果是
![Snipaste_2019-05-25_13-36-09](https://user-images.githubusercontent.com/22662209/58365115-30f41a00-7ef2-11e9-8304-79222287c512.png)
hyper中显示的是
![Snipaste_2019-05-25_13-37-25](https://user-images.githubusercontent.com/22662209/58365123-4b2df800-7ef2-11e9-921d-cece73a297f7.png)
不知道要怎么修改呢

**Comment by spencerwooo** [comment]
其实你可以把 PowerShell 背景颜色改更深一些，就明显了。这个应该最方便的解决方法了吧。

![image](https://user-images.githubusercontent.com/32114380/58369335-8c8ec980-7f2b-11e9-9597-020c11401092.png)

**Comment by Whale-fall** [comment]
其实不是呢，背景颜色里最黑的就是这个图上显示的那个了。应该需要修改的是参数颜色那一项，但是我不知道如何改动。

**Comment by Whale-fall** [comment]
还有一个非常奇怪的事情和你分享下，自从更新到1903版本后除了fluent terminal，wsl只要使用了spaceshio主题，最后一个字的颜色显示就会不对呢，类似于这样（注意两个base的差别）：
![Snipaste_2019-05-25_20-35-03](https://user-images.githubusercontent.com/22662209/58369439-d4fab700-7f2c-11e9-8d6d-e1ef8698b4a5.png)
但是fluent中切换了一次后也会出现异常，我英文不好所以不知道怎么提issue，大佬如果你方便的话可以帮忙反映下这个问题么，我觉得应该是win更新的锅
![Snipaste_2019-05-25_20-37-31](https://user-images.githubusercontent.com/22662209/58369459-2440e780-7f2d-11e9-942f-a3f5b370c00a.png)

**Comment by spencerwooo** [comment]
这...讲道理我觉得应该是 Spaceship 主题的锅。因为 1903 PowerShell 也更新了，所以可能渲染方式也有变化了吧。我也不清楚了，等我遇到这个问题再说。目前我没法复现。

**Comment by Whale-fall** [comment]
好的呢，powershell 6显示的是过时的帮助文档，根本不知道如何单独改动参数一项呜呜呜，谢谢大佬啦
