### ISSUE TITLE
能分享下Windows Terminal 配置么

### ISSUE THREAD

**Issue by brucmao** [spencerwoo98/awesome-alias#5]
按照楼主的方法配置了，Powershell 只能达到这个效果，并且安装了Fantasque Sans Mono 在powershell字体设置中不能找到该字体
![](https://i.loli.net/2019/06/23/5d0f8e8c98a7014757.png)
仔细看了你的截图，应该是Windows Terminal，
可是我安装Windows Terminal后，并没有生效，能否分享下Windows Terminal json配置
![](https://i.loli.net/2019/06/23/5d0f94266231c71411.png)

**Comment by spencerwooo** [comment]
@brucmao 你需要安装的是 Fantasque Sans Mono 的 [Nerd Font 版本](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FantasqueSansMono)，这样才能显示完整的字符。然后为了让 Windows Terminal 的标题栏和底下背景搭配，需要：

1. 将 Windows 主题模式设置为「暗色」
2. 要保证标题栏显示主题颜色
3. 然后将你的主题颜色设置为类似你 Terminal 的背景颜色

这样就能相对完美显示了。

Windows Terminal 的配置文件里面有三个 Profile 分别对应 `Command Prompt`、`PowerShell` 和 `WSL`，每个里面都有一个 background 和一个 theme，里面除了默认主题还内置了 Solarized Dark 和 Solarized Light 这样两个主题， 你分别配置就可以了。

我手头没有 Windows 电脑，稍后再给你补一个 Windows Terminal 的 json 配置文件。🖤

**Comment by brucmao** [comment]
尝试了下：
1.win10修改为暗色模式，并设置标题栏显示主题色
![image](https://user-images.githubusercontent.com/6119652/60108077-9d389680-979a-11e9-95d9-0773506d1c84.png)

![image](https://user-images.githubusercontent.com/6119652/60108104-a4f83b00-979a-11e9-972d-62a1fd6fd159.png)
2.发现主题色没法设置全黑色，系统不允许设置过暗的颜色，导致Windows Terminal 标题栏很奇怪，不知道你时怎么办到的，

3.我下载的[Snazzy](https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Snazzy.itermcolors) 颜色主题为啥和你不一样，
4.怎么提取Snazzy的颜色值放到Windows Terminal 的 json 配置文件中

![image](https://user-images.githubusercontent.com/6119652/60108754-c279d480-979b-11e9-8caa-9fa9a14f4b34.png)

**Comment by spencerwooo** [comment]
@brucmao 这里 [dotfiles/Windows Terminal](https://github.com/spencerwooo/dotfiles#windows-terminal) 我刚刚更新好了，但是我找不到我之前 Snazzy 主题的颜色了 23333，我重新写了一个 Nord 的主题配色，不过你自己再弄一个 Snazzy 也是可以的，道理是一样的。
