### ISSUE TITLE
求助，prompt颜色更改

### ISSUE THREAD

**Issue by Whale-fall** [spencerwoo98/awesome-alias#7]
大佬好，我在参照你的dotfile配置wt终端时，发现颜色显示异常，同一种配色在fluent terminal和在windows terminal下显示不一致，如下：
![image](https://user-images.githubusercontent.com/22662209/74582738-74e7fb80-4ffa-11ea-87c8-9db38f9d46c9.png)
![image](https://user-images.githubusercontent.com/22662209/74582741-803b2700-4ffa-11ea-8c64-808430699e2c.png)
主要是有两点让我觉得难受：
1.wt中prompt好像格子显示的很明显，有什么办法可以让其看起来和谐一点嘛
2.wt中要怎么更改某一部分的配色呢，比如whalefall 的那一部分，我调整了很多次都不能像fluent-terminal中显示的那么清楚。
谢谢！

**Comment by spencerwooo** [comment]
1. 字体问题，可以换别的支持 Powerline 字符的字体，比如搜索 Nerd Font 即可
2. 配色不是 Windows Terminal 的 Profile 里面修改的，而是在 oh-my-posh 的主题文件中修改，这里的颜色定义位于 `... -Object "$user@$computer " -ForegroundColor $sl.Colors.PromptForegroundColor ...` 里面的 `$sl.Colors.PromptForegroundColor`，这里修改即可

![image](https://user-images.githubusercontent.com/32114380/74587458-7ed72200-502d-11ea-8a6b-a6ea725075cd.png)
