### ISSUE TITLE
Windows Terminal 更新后出现问题

### ISSUE THREAD

**Issue by WangTingZheng** [spencerwoo98/awesome-alias#8]
第一个是Windows Terminal的上面变成了和系统一样的配色，整个界面不是全黑了
![image](https://user-images.githubusercontent.com/32613835/82111132-67ffb300-9775-11ea-923c-d0a49e6e69a7.png)
第二个是global标签被舍弃了，需要更新

**Comment by spencerwooo** [comment]
谢谢提醒 等有时间我更新上
